/**
 * Mock for the Discover screen's live business hook.
 */
export const mockDiscoverBusinessesModule = () => ({
  useDiscoverBusinesses: jest.fn(() => ({
    data: [
      {
        id: 'urban-grill',
        image: { uri: 'https://example.test/logo.png' },
        name: 'Urban Grill & Bistro',
        category: 'Food & Dining',
        categoryFilter: 'Food & Dining',
        imageAlt: 'Urban Grill & Bistro',
        rating: '',
        reviews: 0,
        distance: '',
        location: 'Apo Boulevard, Abuja',
        activeDealLabel: '',
        status: { label: 'Verified Partner', icon: 'verified' },
        branchCode: 'URBANGRLL',
      },
      {
        id: 'glow-serenity',
        image: { uri: 'https://example.test/logo.png' },
        name: 'Glow & Serenity Spa',
        category: 'Beauty & Wellness',
        categoryFilter: 'Beauty & Wellness',
        imageAlt: 'Glow & Serenity Spa',
        rating: '',
        reviews: 0,
        distance: '',
        location: 'Maitama Heights',
        activeDealLabel: '',
        status: { label: 'Verified Partner', icon: 'verified' },
        branchCode: 'GLOWSERE',
      },
      {
        id: 'sole-district',
        image: { uri: 'https://example.test/logo.png' },
        name: 'Sole District Boutique',
        category: 'Fashion & Apparel',
        categoryFilter: 'Fashion & Apparel',
        imageAlt: 'Sole District Boutique',
        rating: '',
        reviews: 0,
        distance: '',
        location: 'Area 11 Arcade',
        activeDealLabel: '',
        status: { label: 'VEMTAP Exclusive', icon: 'exclusive' },
        branchCode: 'SOLEDIST',
      },
      {
        id: 'sky-lounge',
        image: { uri: 'https://example.test/logo.png' },
        name: 'The Sky Lounge & Grill',
        category: 'Food & Dining',
        categoryFilter: 'Food & Dining',
        imageAlt: 'The Sky Lounge & Grill',
        rating: '',
        reviews: 0,
        distance: '',
        location: 'Maitama Heights, Abuja',
        activeDealLabel: '',
        status: { label: 'Verified Partner', icon: 'verified' },
        branchCode: 'SKYLOUNG',
      },
      {
        id: 'cafe-neo',
        image: { uri: 'https://example.test/logo.png' },
        name: 'Cafe Neo Artisanal',
        category: 'Food & Dining',
        categoryFilter: 'Food & Dining',
        imageAlt: 'Cafe Neo Artisanal',
        rating: '',
        reviews: 0,
        distance: '',
        location: 'Wuse II',
        activeDealLabel: '',
        status: { label: 'Verified Partner', icon: 'verified' },
        branchCode: 'CAFENEO',
      },
    ],
    isLoading: false,
    isError: false,
  })),
});
