export const strings = {
  app: {
    name: 'Vemtap',
    tagline: 'One Tap. Lifetime Customer.',
  },
  common: {
    loading: 'Loading…',
    retry: 'Retry',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    error: 'Something went wrong. Please try again.',
    offline: 'You are offline. Some features may be unavailable.',
    empty: 'Nothing here yet.',
    next: 'Next',
    getStarted: 'Get Started',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    skip: 'Skip',
    goBack: 'Go back',
  },
  onboarding: {
    welcomeHeadline: 'Discover More.\nBuy Smarter.',
    welcomeSubtitle:
      'Find great deals, products and businesses around you — all in one place.',
    welcomeBadge: 'Fast & Local',
    welcomeLocation: 'Lagos Near You',
    welcomeMicro1: 'Bakery & Cafe',
    welcomeMicro1Sub: 'Buy 1 Get 1',
    welcomeMicro2: '1,420+ Deals',
    welcomeMicro2Sub: 'Updated 2m ago',
    welcomeVerified: 'Verified Stores',
    welcomePickup: 'Instant Pickup',
    welcomeThermometer: 'Artisan Gourmet & Co.',
    welcomeThermometerLoc: '0.4 km • Lekki Phase 1',
    welcomeBogo: '35% OFF TODAY',
    alreadyHaveAccount: 'Already have an account?',
    discoverHeadline: 'Discover Deals Near You',
    discoverSubtitle:
      'See offers from businesses around your location and find something worth buying nearby.',
    discoverTip: 'Deals refresh in real-time as you move around town',
    startHeadline: "Let's find what's near you.",
    startSubtitle: 'Discover deals, products and businesses around your location.',
    ownABusiness: 'Own a business?',
    setUpBusiness: 'Set up your business on VEMTAP →',
  },
  auth: {
    emailPlaceholder: 'Email address',
    passwordPlaceholder: 'Password',
    invalidCredentials: 'Invalid email or password.',
  },
  errors: {
    network: 'Network error. Check your connection.',
    timeout: 'Request timed out. Please try again.',
    unauthorized: 'Your session has expired. Please sign in again.',
    forbidden: 'You do not have permission to do that.',
    notFound: 'Not found.',
    validation: 'Please check the highlighted fields.',
    server: 'Server error. Please try again later.',
  },
} as const;
