export const strings = {
  app: {
    name: 'Vemtap',
    tagline: 'One Tap. Lifetime Customer.',
  },
  common: {
    loading: 'Loading…',
    retry: 'Retry',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    error: 'Something went wrong. Please try again.',
    offline: 'You are offline. Some features may be unavailable.',
    empty: 'Nothing here yet.',
    next: 'Next',
    getStarted: 'Get Started',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    skip: 'Skip',
    goBack: 'Go back',
  },
  onboarding: {
    welcomeHeadline: 'Discover More.\nBuy Smarter.',
    welcomeSubtitle:
      'Find great deals, products and businesses around you — all in one place.',
    welcomeBadge: 'Fast & Local',
    welcomeLocation: 'Lagos Near You',
    welcomeMicro1: 'Bakery & Cafe',
    welcomeMicro1Sub: 'Buy 1 Get 1',
    welcomeMicro2: '1,420+ Deals',
    welcomeMicro2Sub: 'Updated 2m ago',
    welcomeVerified: 'Verified Stores',
    welcomePickup: 'Instant Pickup',
    welcomeThermometer: 'Artisan Gourmet & Co.',
    welcomeThermometerLoc: '0.4 km • Lekki Phase 1',
    welcomeBogo: '35% OFF TODAY',
    alreadyHaveAccount: 'Already have an account?',
    discoverHeadline: 'Discover Deals\nNear You',
    discoverSubtitle:
      'See offers from businesses around your location and find something worth buying nearby.',
    discoverTip: 'Deals refresh in real-time as you move around town',
    startHeadline: "Let's find what's\nnear you.",
    startSubtitle: 'Discover deals, products and businesses around your location.',
    ownABusiness: 'Own a business?',
    setUpBusiness: 'Set up your business on VEMTAP →',
  },
  auth: {
    emailPlaceholder: 'Email address',
    passwordPlaceholder: 'Password',
    invalidCredentials: 'Invalid email or password.',
    signInHeader: 'Sign In',
    signInTitle: 'Welcome Back',
    signInSubtitle:
      'Sign in to access your claimed deals, saved favorites, and local offers.',
    signInOr: 'or sign in with',
    signInIdentifierLabel: 'Email or Phone Number',
    signInIdentifierPlaceholder: 'name@example.com or +234...',
    signInIdentifierError: 'Enter your email or phone number',
    signInCredentialLabel: 'PIN or Password',
    signInCredentialPlaceholder: '••••••',
    signInCredentialError: 'Enter your PIN or password',
    signInForgot: 'Forgot?',
    signInRemember: 'Keep me signed in on this device',
    signInToggleVisibility: 'Toggle password visibility',
    signInShowPassword: 'Show password',
    signInHidePassword: 'Hide password',
    signInNoAccount: "Don't have an account?",
    signInCreateAccount: 'Create an account',
    signInOwnBusiness: 'Own a Business?',
    signInOwnBusinessSub: 'Click here to Register.',
    registerStepOf: (step: number, total: number) => `Step ${step} of ${total}`,
    registerWelcomeTitle: 'Welcome to VEMTAP',
    registerWelcomeSubtitle:
      'Create your account or sign in to save deals and claim exclusive offers near you.',
    registerContinueWithGoogle: 'Continue with Google',
    registerOr: 'OR',
    registerEmailLabel: 'Enter your email to continue',
    registerEmailPlaceholder: 'name@example.com',
    registerEmailHint:
      "We'll send you a 6-digit verification code to confirm your email.",
    registerContinue: 'Continue',
    registerSendingCode: 'Sending code...',
    registerCodeSent: 'Code Sent!',
    registerHaveAccount: 'Already have an account?',
    registerTermsPrefix: "By continuing, you agree to VEMTAP's ",
    registerTerms: 'Terms of Service',
    registerAnd: ' and ',
    registerPrivacy: 'Privacy Policy',
    registerEncrypted: '256-bit encrypted authentication',
    registerOwnBusiness: 'Own a Business?',
    registerOwnBusinessSub: 'Register your store & publish offers',
    registerRegisterHere: 'Register Here',
    otpHeader: 'Otp Code Verification',
    otpTitle: 'Verify your email',
    otpSubtitle: 'We sent a 6-digit verification code to',
    otpMaskedEmail: 'jo****@gmail.com',
    otpEditEmail: 'Edit email address',
    otpDidntReceive: "Didn't receive it?",
    otpResend: 'Resend code',
    otpResendTimer: (s: number) => `(0:${String(s).padStart(2, '0')})`,
    otpSpamHint:
      "Check your spam, junk, or promotions folder if you don't see the code in your main inbox within a few moments.",
    otpContinue: 'Continue',
    otpUseDifferentEmail: 'Use a different email address',
    profileHeader: 'Profile Setup',
    profileTitle: 'Tell us about yourself',
    profileSubtitle:
      'Complete your profile and set your security PIN to access your account and claimed deals.',
    profilePersonalInfo: 'Personal Information',
    profileFirstName: 'First name',
    profileFirstNamePlaceholder: 'e.g. John',
    profileLastName: 'Last name',
    profileLastNamePlaceholder: 'e.g. Doe',
    profilePhone: 'Phone number',
    profilePhonePlaceholder: '801 234 5678',
    profilePinCardTitle: 'Create your 6-digit PIN',
    profilePinEncrypted: 'Encrypted',
    profilePinHelper:
      'This 6-digit PIN will be your primary access credential to sign in and confirm deal claims.',
    profileCreatePin: 'Create 6-digit PIN',
    profileConfirmPin: 'Confirm your 6-digit PIN',
    profilePinCounter: (n: number) => `${n} / 6 entered`,
    profilePinMatches: 'PIN Matches',
    profilePinMismatch: 'PINs do not match',
    profilePinSecurity: 'Your PIN is encrypted and securely stored.',
    profileBenefitTitle: 'Instant Claim Verification',
    profileBenefitBody:
      'Never wait for SMS codes at checkout. One tap with your PIN redeems offers instantly.',
    profileCompleteSetup: 'Complete Setup',
    profileNextLabel: 'Next:',
    profileNextLocation: 'Set up your location to discover deals near you →',
    locationPermissionTitle: "What's near you?",
    locationPermissionBody:
      'Allow VEMTAP to use your location so we can show you relevant deals, businesses and products around you.',
    locationUseMyLocation: 'Use My Location',
    locationFinding: 'Finding nearby gems...',
    locationSet: 'Location Set!',
    locationEnterManually: 'Enter Location Manually',
    locationPrivacy: 'Your location helps us personalize what you discover.',
    locationCafeAroma: 'Cafe Aroma',
    locationCafeBadge: '20% OFF',
    locationSneakers: 'Sneakers & Apparel',
    locationBistro: 'Bistro Grill',
    locationBistroKm: '0.3 km',
    locationRating: '4.9',
    locationRatingCount: '(1.2k)',
    manualHeader: 'Select Neighborhood',
    manualChip: 'Hyper-local Discovery',
    manualTitle: 'Where are you?',
    manualSubtitle: "Enter a city, area or location to discover what's nearby.",
    manualSearchPlaceholder: 'Search city, area or location',
    manualClearSearch: 'Clear search input',
    manualMapCaption: 'FCT Zone • Apo Sector Active',
    manualOffersBadge: '142 Offers Nearby',
    manualUseCurrent: 'Use Current Location',
    manualUseCurrentSub: 'GPS accurate • Instant local calibration',
    manualSuggested: 'Suggested Areas',
    manualRegion: 'Abuja Urban Core',
    manualSelected: 'Selected',
    manualAreaSub: 'Abuja, Federal Capital Territory',
    manualInsightTitle: 'Active Flash Drops',
    manualInsightBody: 'Local merchant vouchers refreshing in Apo every 20 mins.',
    manualContinueWith: (area: string) => `Continue with ${area}`,
    manualOwnVenue: 'Own a local venue?',
    manualSetupVemtap: 'Set up on VEMTAP',
    confirmHeader: 'Confirm Location',
    confirmEyebrow: 'Location Confirmed',
    confirmTitle: "You're exploring around",
    confirmArea: 'Apo, Abuja',
    confirmRegion: 'Federal Capital Territory',
    confirmRadius: '5 km discovery radius',
    confirmActiveArea: 'Active Area',
    confirmHub: 'Apo Hub',
    confirmDeals: '48 Deals',
    confirmCafes: '12 Cafes',
    confirmStores: '18 Stores',
    confirmRadiusChip: 'Deals & Stores within 5km',
    confirmChangeLocation: 'Change location',
    confirmContinue: 'Continue',
    confirmOwnBusiness: 'Own a business?',
    confirmingSetup: 'VEMTAP RADAR',
    discoveringTitle: "Finding what's around you...",
    discoveringBody: 'Discovering deals, businesses and products near you.',
    discoveringTag: 'Personalizing your local feed',
    discoveringHint: 'Preparing exclusive perks • Ready in a moment',
    discoveringCafeNeo: 'Cafe Neo',
    discoveringCafeDiscount: '-25%',
    discoveringCafeDeal: 'Buy 1 Get 1 Free',
    discoveringSole: 'Sole District',
    discoveringSoleSub: 'Weekend Special',
    discoveringNewDeals: '34 New Deals',
    discoveringArea: 'Apo • Within 3km',
    discoveringStatuses: [
      'Scanning Apo, Abuja...',
      'Gathering merchant discounts...',
      'Curating nearby exclusives...',
      'Welcome to VEMTAP!',
    ] as const,
    discoveringProgress: [45, 78, 94, 100] as const,
  },
  home: {
    greeting: 'Good evening',
    location: 'Apo, Abuja',
    radius: 'Within 5 km',
    notifications: 'Notifications',
    searchPlaceholder: 'Search deals, businesses or products',
    filter: 'Filter options',
    categories: [
      'All',
      '🍔 Food',
      '👟 Fashion',
      '✨ Beauty',
      '⚡ Electronics',
      '🛒 Groceries',
      '💆 Services',
    ] as const,
    featured: 'Featured Deals',
    promoted: 'Promoted',
    dealsNearYou: 'Deals Near You',
    trending: 'Trending Deals',
    businessesAround: 'Businesses Around You',
    popularNearYou: 'Popular Near You',
    seeAll: 'See All',
    listView: 'List view',
    gridView: 'Grid view',
    listViewActive: 'List view (active)',
    gridViewActive: 'Grid view (active)',
    share: 'Share',
    partner: 'Partner',
    verified: 'Verified',
    hot: 'Hot',
    activeDeals: (n: string) => `${n} Active Deals`,
    specialOffers: 'Special Offers',
    enrollmentPrompt: 'Own a local business in Abuja?',
    enrollmentLink: 'Put your deals on VEMTAP',
    enrollmentMeta: 'Set up in 3 minutes • Instant discovery',
    tabHome: 'Home',
    tabDeals: 'Deals',
    tabDiscover: 'Discover',
    tabSaved: 'Saved',
    tabAccount: 'Account',
    avatar: 'Account avatar',
  },
  deals: {
    caption: 'Deals',
    location: 'Apo, Abuja',
    radius: 'Within 5 km',
    notifications: 'Notifications',
    searchPlaceholderDots: 'Search deals, businesses or products...',
    filters: 'Filters',
    featuredEyebrow: 'Featured Deal of the Day',
    featuredPercentOff: '50% OFF',
    topPick: 'Top Pick',
    specialPromo: 'Special Promo',
    endsIn8h: 'Ends in 8h',
    saveN: (amount: string) => `Save ${amount}`,
    limitedVouchers: 'Limited to 30 vouchers',
    claimDeal: 'Claim Deal',
    claim: 'Claim',
    dealsInTitle: (area: string) => `Deals in ${area}`,
    dealsInCount: (n: number) => `(${n})`,
    dealsInFound: (n: number) => `(${n} found)`,
    showingDeals: (n: number) => `Showing ${n} deals`,
    listView: 'List view',
    gridView: 'Grid view',
    avatar: 'Account avatar',
    verified: 'Verified',
    dealDetail: 'Deal Detail',
    claimNow: 'Claim Now',
    viewingDeal: 'Viewing deal details',
    dealClaimed: 'Deal claimed successfully',
    dealSavedToFavorites: 'Saved to favorites',
    dealShare: 'Share deal',
    dealLike: 'Like this deal',
  },
  filters: {
    title: 'Filters',
    reset: 'Reset',
    activeSummary: (n: number) => `${n} active filters applied`,
    matchingPromos: (n: number) => `Matching ${n} local verified promotions`,
    active: 'Active',
    distance: 'Distance',
    withinKm: (n: number) => `Within ${n} km`,
    distanceSubtitle: 'Show deals within your immediate range',
    nearMe: 'Near Me',
    oneKm: '1 km',
    fiveKm: '5 km',
    tenKm: '10 km',
    custom: 'Custom',
    minKm: (n: number) => `Min: ${n} km`,
    maxKm: (n: number) => `Max: ${n} km`,
    areaApo: 'Apo District',
    areaCentral: 'Central Area',
    areaGwarinpa: 'Gwarinpa',
    category: 'Category',
    categorySubtitle: 'Select one or multiple categories',
    selectedCount: (n: number) => `${n} Selected`,
    priceRange: 'Price Range',
    priceSubtitle: 'Nigerian Naira (₦) budget limits',
    anyPrice: 'Any Price',
    under5k: 'Under ₦5,000',
    range5to20: '₦5,000 – ₦20,000',
    range20to50: '₦20,000 – ₦50,000',
    over50k: '₦50,000+',
    minimum: 'Minimum',
    maximum: 'Maximum',
    discount: 'Discount Percentage',
    discountSubtitle: 'Minimum guaranteed reduction',
    anyDiscount: 'Any Discount',
    off10: '10%+',
    off20: '20%+',
    off30: '30%+',
    off50Hot: '50%+ Hot Deals',
    availability: 'Availability & Timing',
    availabilitySubtitle: 'Filter by redemption windows and convenience',
    availableNow: 'Available Now',
    availableNowSub: 'Immediate voucher redemption',
    endingSoon: 'Ending Soon',
    endingSoonSub: 'Expiring within 24 hours',
    walkIns: 'Walk-ins Accepted',
    walkInsSub: 'No prior reservation required',
    weekendOnly: 'Weekend Only Deals',
    weekendOnlySub: 'Valid on Saturday & Sunday',
    redeemTitle: 'VEMTAP Tap-to-Redeem',
    redeemBody:
      'All filtered results support instant contactless discount verification at checkout.',
    showDeals: (n: number) => `Show ${n} Deals`,
    showingNear: (area: string) => `Showing deals near ${area}`,
    foodDrinks: 'Food & Drinks',
    beautySpa: 'Beauty & Spa',
  },
  errors: {
    network: 'Network error. Check your connection.',
    timeout: 'Request timed out. Please try again.',
    unauthorized: 'Your session has expired. Please sign in again.',
    forbidden: 'You do not have permission to do that.',
    notFound: 'Not found.',
    validation: 'Please check the highlighted fields.',
    server: 'Server error. Please try again later.',
  },
} as const;
