# Frozen string literal: true

default_platform(:android)

platform :android do
  desc "Build and upload a beta AAB to Google Play (internal track)"
  lane :beta do
    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "./"
    )
    upload_to_play_store(
      track: "internal",
      aab: "../app/build/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Run unit tests"
  lane :test do
    gradle(task: "test")
  end
end
