/**
 * Screen-local copy for the business setup flow.
 * Verbatim from stitch_vemtap_design_system_1/**\/code.html — kept out of
 * @constants/strings because these screens are not wired to navigation yet.
 */
export const businessIntroCopy = {
  header: 'Business Profile',
  title: 'Turn Nearby Foot Traffic into Lifetime Customers',
  subtitle:
    'VEMTAP gives your physical store or service business the digital superpower to attract, engage, and retain shoppers within your immediate district.',
  storeDistrict: 'Apo District • Abuja',
  zeroCommission: 'Zero Commission',
  footfallLabel: 'Nearby Footfall',
  footfallValue: '1,420 Active Shoppers',
  returnLabel: 'Avg. Return',
  returnValue: '+34% / Mo',
  pulseTitle: 'Direct Consumer Settlement',
  pulseBody: 'Keep 100% of your counter revenue',
  audienceTitle: 'Estimated Walking Audience',
  audienceHint:
    'Adjust range to preview potential foot traffic around your storefront location:',
  audienceRangeMin: '0.5km',
  audienceRangeMax: '3.5km',
  audienceReady: 'local users ready to tap',
  audienceDensityHigh: 'High Density',
  pillarsTitle: 'What VEMTAP Does for You',
  pillarsSubtitle: 'Everything needed to dominate local retail & service footfall',
  pillarsToggle: '8 Core Tools',
  testimonial:
    'Within 10 days of listing in Apo, we recorded over 120 voucher redemptions from nearby residents.',
  testimonialAuthor: 'Amara K. • Founder, Bloom Wellness & Cafe',
  freeToJoin: 'Free to join',
  noSetupFees: 'No setup fees',
  verifiedMerchants: 'Verified merchants',
  setUpBusiness: 'Set Up My Business',
  learnMore: 'Learn How VEMTAP Works',
} as const;

export const businessProfileCopy = {
  basicInfo: {
    header: 'Basic Information',
    step: 'Step 1 of 3: Basic Info',
    percent: '33% Complete',
    title: 'Tell us about your business',
    subtitle:
      'This information helps local customers discover your store and services across your district.',
    trustTitle: 'District Verified Profile',
    trustBody:
      'Your business details are verified before publishing to shoppers in your district.',
    nameLabel: 'Business Name',
    namePlaceholder: 'e.g. Oak Street Market',
    categoryLabel: 'Primary Category (Required)',
    categoryPlaceholder: 'Choose a category',
    changeCategory: 'Change',
    categoryFirst: 'Pick a category first to choose a specialty.',
    specialtyEmpty: 'No specialty selected yet.',
    categoryHint:
      'Helps assign your store to the right category carousel on nearby feeds.',
    specialtyLabel: 'Subcategory Specialty',
    specialtyHint: '(Select up to 2)',
    descriptionLabel: 'Storefront Description',
    descriptionPlaceholder: 'Introduce what makes your business special...',
    descriptionHint: 'Appears on your deal cards and search results.',
    previewLabel: 'Consumer Card Preview',
    previewBadge: 'Live Preview',
    previewDistrict: 'Within your district',
    previewEmptyTitle: 'Your Store Name',
    previewEmptySubtitle: 'Select specialty',
    continue: 'Continue to Branding',
    saveDraft: 'Save as Draft',
  },
  branding: {
    header: 'Media And Branding',
    step: 'Step 2 of 3',
    percent: '66% Complete',
    stageOne: '1. Business Info',
    stageTwo: '2. Visual Branding',
    stageThree: '3. Channels',
    title: 'Upload your brand visuals',
    subtitleLead: 'Businesses with high-quality photos get up to',
    subtitleHighlight: '40% more deal views',
    subtitleTail: 'and customer walk-ins.',
    tip: 'Crisp, natural lighting turns first-time scrollers into immediate table reservations.',
    logoTitle: 'Store Logo',
    logoSpec: 'Square 1:1 (PNG, JPG max 5MB)',
    logoBody: 'Used on customer vouchers, map pins, and header badges.',
    logoEmblem: 'BISTRO',
    logoChange: 'Change',
    logoRemove: 'Remove',
    logoHint: 'Optimal resolution: 400 × 400px',
    coverTitle: 'Storefront Cover Banner',
    coverSpec: '16:9 Recommended',
    coverBody: 'Primary banner shown on your business profile and search cards.',
    coverDimensions: '1200 × 675px',
    coverReplace: 'Replace Cover Photo',
    coverFormats: 'JPG, WEBP up to 10MB',
    galleryTitle: 'Interior & Product Photos',
    galleryBody: 'Add up to 5 photos showcasing your space, menu, or products.',
    galleryAdd: 'Add Photo',
    previewTitle: 'Live Feed Preview',
    previewHint: 'How customers see you',
    previewBadge: '20% OFF FIRST VISIT',
    previewOpen: 'Open Now',
    previewName: 'Urban Grill & Bistro',
    previewMeta: 'American Fusion • Casual Dining • 0.3 mi away',
    continue: 'Continue to Contact & Channels',
    back: 'Back',
    saveDraft: 'Save as Draft',
  },
  contactChannels: {
    header: 'Basic Information',
    step: 'Step 3 of 3',
    percent: '100% Complete',
    finalStep: 'Final Step',
    title: 'How customers connect with you',
    subtitle:
      'Make it easy for local customers to ask questions, place orders, and coordinate voucher redemptions.',
    required: 'Required',
    phoneLabel: 'Primary Business Phone / WhatsApp',
    phonePlaceholder: '800 000 0000',
    phoneHint: 'Used for voucher redemption verification codes and customer queries.',
    emailLabel: 'Official Business Email',
    emailPlaceholder: 'support@yourbusiness.ng',
    emailHint: 'For settlement invoices and official platform notices.',
    websiteLabel: 'Website or Online Menu (Optional)',
    websitePlaceholder: 'https://yourmenu.com',
    socialTitle: 'Social & Messaging Presences',
    socialBody: 'Showcases trust icons directly on your profile card',
    socialAdd: 'Add a social presence',
    whatsappLabel: 'WhatsApp Direct',
    editHandle: 'Edit handle',
    preferencesTitle: 'Direct Customer Contact Preferences',
    chatLabel: 'Allow In-App Direct Chat',
    chatBadge: 'Fast',
    chatBody: 'Recommended - customers expect quick replies within 15 minutes.',
    whatsappAlertsLabel: 'Receive deal claims via WhatsApp alerts',
    whatsappAlertsBody:
      'Instant notification ping each time a nearby customer claims your voucher.',
    launchTitle: 'Almost Ready to Launch!',
    launchBody: 'Urban Grill Lagos will be visible to 1,420+ food lovers within 3 km.',
    complete: 'Complete Profile Setup',
    saveDraft: 'Save as Draft',
  },
} as const;

export const businessLocationCopy = {
  whereLocated: {
    header: 'Location Details',
    step: 'Step 2 of 4 • Business Location',
    percent: '50% Complete',
    title: 'Where is your business located?',
    subtitle:
      'Customers will use this information to discover your business and redeem local offers near them.',
    searchPlaceholder: 'Search street, landmark, or area...',
    clearSearch: 'Clear location search',
    useCurrentLocation: 'Use current location',
    gpsReady: 'GPS Ready',
    mapPinLabel: 'Urban Grill & Bistro (Main)',
    mapPinTag: 'Store Entrance',
    mapLayers: 'Map layers',
    mapRecenter: 'Recenter map',
    mapHint: 'Drag pin to adjust exact storefront entrance',
    territoryTitle: 'Territory Resolution',
    territoryBadge: 'Auto-Verified',
    countryLabel: 'Country',
    country: 'Nigeria',
    stateLabel: 'State / Region',
    state: 'FCT (Abuja)',
    cityLabel: 'City / Metro',
    city: 'Abuja Municipal',
    districtLabel: 'District / Area',
    district: 'Wuse 2',
    clusterTitle: 'District Cluster Assignment',
    clusterName: 'Wuse Commercial Hub Cluster #04',
    clusterStatus: 'Assigned',
    clusterBody:
      'Customers browsing within this 3km retail radius will see your flash offers and tap-to-pay deals instantly.',
    clusterInfo: 'More cluster details',
    detailsTitle: 'Storefront Details',
    detailsBadge: 'Editable',
    streetLabel: 'Street / Building Address',
    landmarkLabel: 'Landmark / Suite / Floor',
    landmarkPlaceholder: 'e.g. Opposite City Mall, 2nd Floor',
    continue: 'Continue to Branch Details',
    saveDraft: 'Save as Draft',
  },
  locations: {
    header: 'Location Details',
    step: 'Step 2 of 4',
    percent: '60% Complete',
    title: 'Your Business Locations',
    subtitleLead:
      'Add your other locations so customers across different districts can discover them too. All branches are',
    subtitleActive: 'Active',
    subtitleTail: 'during your free trial.',
    multiTitle: 'Does your business have other locations?',
    multiLabel: 'Yes, we operate in multiple locations',
    multiBody:
      'All locations remain active during your 30-day free trial. If unchecked, your primary location will be your sole operating branch.',
    editBranch: 'Edit Branch',
    manageHours: 'Manage Hours',
    addBranch: '+ Add Another Branch Location',
    addBranchBody: 'Opens branch setup form & manager/lead contact assignment',
    continue: 'Continue to Products & Services',
    footnote: 'You can add more locations anytime from your business settings.',
    conciergeLead: 'Need custom territorial management?',
    concierge: 'Contact Concierge',
  },
  addBranch: {
    header: 'Add Branch Location',
    eyebrow: 'Expansion Studio',
    title: 'Add Branch Location',
    subtitle: 'Expand your customer reach and empower local store leads with one tap.',
    inheritTitle: 'Inherits Brand Identity',
    inheritBody:
      'This branch automatically shares your primary business logo, storefront branding, and verified category badges. No extra media uploads required!',
    identityTitle: 'Branch Identification',
    nameLabel: 'Branch / Location Name',
    namePlaceholder: 'e.g. Garki Branch, Victoria Island Annex',
    locationTitle: 'Physical Location & Address',
    gpsLinked: 'GPS Linked',
    streetLabel: 'Street / Building Address',
    streetPlaceholder: 'e.g. Suite 4B, Garki Mall, Area 11',
    landmarkLabel: 'Landmark / Floor',
    landmarkPlaceholder: 'e.g. Opposite National Hospital, Ground Floor',
    districtLabel: 'City / District',
    districtPlaceholder: 'e.g. Abuja Municipal • Garki District',
    coordinates: '9.0348° N, 7.4891° E',
    coordinatesHint: 'Pinned with ±3m accuracy',
    changeGps: 'Change GPS',
    contactTitle: 'Branch Contact Information',
    phoneLabel: 'Branch Phone Number',
    phonePlaceholder: '801 234 5678',
    emailLabel: 'Branch Direct Email',
    emailPlaceholder: 'e.g. garki@urbangrill.ng',
    leadTitle: 'Person in Charge / Branch Lead',
    leadBody:
      'Who manages orders, customer inquiries, and voucher redemptions at this branch?',
    leadSuggestedTitle: 'Suggested Title',
    leadRoleLabel: 'Role / Title Title',
    leadRolePlaceholder: 'e.g. Branch Manager, Store Lead, Supervisor',
    leadNameLabel: 'Full Name',
    leadNamePlaceholder: 'e.g. Chidinma Okafor',
    leadEmailLabel: 'Direct Email Address',
    leadEmailPlaceholder: 'e.g. chidinma@urbangrill.ng',
    leadPhoneLabel: 'Direct Phone / WhatsApp Number',
    leadPhonePlaceholder: '803 000 0000',
    grantAccess: 'Grant dashboard access',
    grantAccessBody: 'Allows managing vouchers, local menu & reviews',
    hoursTitle: 'Operating Hours',
    hoursLabel: 'Mon - Sun Standard',
    hoursValue: '8:00 AM – 10:00 PM (Daily)',
    hoursEdit: 'Edit',
    hoursCustomize: 'Customize specific day hours',
    save: 'Save & Add Branch Location',
    cancel: 'Cancel & Return to Locations',
  },
} as const;

export const businessCatalogCopy = {
  header: 'Location Details',
  step: 'Step 3 of 4 • Offerings',
  percent: '75% Complete',
  title: 'Add your products or services',
  subtitle:
    'Add what you offer so customers can discover, order, and engage with your business storefront across all active locations.',
  addProduct: 'Add Product',
  addProductBody: 'Retail, Food & Drinks, physical inventory items.',
  addService: 'Add Service',
  addServiceBody: 'Spa sessions, salon, dining tasting experiences.',
  availabilityTitle: 'Catalog Availability',
  availabilityBadge: 'Live',
  availabilityLead: 'Synced across',
  availabilityHighlight: '2 active locations',
  availabilityTail:
    '(Wuse & Garki branches). You can set custom regional prices per store.',
  currentCatalog: 'Current Catalog',
  filter: 'Filter',
  editItem: 'Edit item',
  removeItem: 'Remove item',
  addAnother: '+ Add Another Item or Menu Bundle',
  continue: 'Continue to First Deal Setup',
  skip: "Skip for now, I'll add items later",
} as const;

/**
 * Copy for the live category picker. The labels the screens offer come from the
 * API's taxonomy, so only the surrounding chrome is written here.
 */
export const businessCategoryCopy = {
  title: 'Choose Your Category',
  categoryLabel: 'Primary Category',
  subcategoryLabel: 'Subcategory Specialty',
  limitHint: (limit: number) => `Select up to ${limit}`,
  pickCategoryFirst: 'Pick a category to see its specialties.',
  noSubcategories: 'This category has no specialties yet.',
  confirm: 'Save Category',
  loading: 'Loading categories…',
  emptyTitle: 'No categories available',
  emptyBody: 'Categories could not be loaded. Check your connection and try again.',
  errorTitle: 'Could not load categories',
  errorBody: 'Something went wrong fetching the category list.',
  retry: 'Try again',
  summary: (category: string, specialties: string) =>
    specialties ? `${category} • ${specialties}` : category,
} as const;
