/**
 * Screen-local copy for the business verification / registration / trial screens.
 * Verbatim from stitch_vemtap_design_system_1/**\/code.html — kept out of
 * @constants/strings because these screens are not wired to navigation yet.
 */
export const verificationImages = {
  verifiedStorefront:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuBeoDqzO4anB8Z-TU6M-cbD3FQJO-Ip7BzoIsvYZJaOZhcKc7ntuU4bR_ZugHITIMPdjNhg5aBnPkz1omKk8iA6CvNRqbSSfmiHjCMijjw2UANIVzgXlkrnYgguwiQqQY3BAZCu1PSUO1eKTPE0mqQYuTJJhCBd8k6dhqFzHiK-563AAUlOj-cm0UN0aU3l9U1SoGltJeYsMxuI07jAEz2GBpP48CkpTD01PKphMVZQn71RHylcoHyVWQ',
  cacStorefront:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuA0zii5gSszMBCXy4x3QIkdgB7Zixtmh9cDepHQcvEz5KC5VugAI-95LYUhMHatMF7msTNf4ZyIuQPHPey06MAX05cQHB2qUB-5obtIywYNXfjHMkAtIWCXQHm_i_5bIzkoQ2Afv8JxKvsX9s1BUO6MgCkFU_F0lkaJyh8_T0PZ8blgEEtNq31NC0gGpScmK0KbaRpRJpJ0FZOWm8WTFI5KMTqyRHVeA_OHm1yNoUBzRcumlsEnfyHsBA',
  statusCenterLogo:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDJrd5hM47CGoRMa-U22chjZbV7YcR3uH_BbNcba1dcLRWwWEE-5jMtNp8eFVqsdqYcgJkbVqno04Oe9PcrlkCVd_ScXqOX2U5w40qAQvA7_CbYYkeQ9dEenFs9BSqTXlFXrwdbxdELvCfOLB_ui8LvPbPhplOsW1lQG_gQ4QuFiEnV1_KK2IWzytyLuTavKjEZDTI52nxf35QwfmG542bfybV9P49UH9hMIhBDf9-jkQdjtsMYmqK1jw',
  endingStorefront:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuCf1bbGzmyknuRv6JJjZob16_tE3Rl83Fln41x6CqCXX8OVvYrxsHkmLDBBx89eBWIpmX18hXeGHaxIYD6ydAk_ZlxHQE82eaGn76pyXv_pBIyg66F46WT1wkBg-MKWxOoOgGYeT15wOcB3A7r-jL4Lx64FAulOZQLYvRmn782nf7chBB0qof3mzi8yHrjHtslTRpb2k8P1NF36d8VSt8rIvZsuX_0QzeVoctjvJugy4flJq-BEgPmOwg',
  savedCatalog:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuBPA0XxFKh69aQwtXHsVBJ5iVpv5jcrtCnttwgAR43od2GHvYcpvFrt9jXnYm2vHrTMy7_IplosEtgj6WX8YaSsMcsSUH-ltorP-3hzho9rA91cvFuOfTabR11C4snJaBaFb_ssdpJdC6OoEnujYHXxNPzdbyY1whQsZxpGbmdi6bHbqMk-HCONWzn6vdZd9EF_fjyLmQKw4o5QRRuwvFk0UfZNlF3dUQGXSWFCkm8KaCAWTQrmCYRYuQ',
  savedOutlet:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuBYFJT-yPSlL19UQset5SjCKMOeTO1BlmIO273u76iEPUGTQILq3w6S5Odjk49TaIGm6FAuk_OjVq2tZcZsGh0xrvOC-R8HJ5oaQ2EcXs6jCM2Ui8s9PkKHgkQGg2A_c3ZdlkPRkkMa4NR6rkjkWNStUs07FiREjLPjQcA069sA49DEeSKOiR4K42xS2o25es8xqlQS808Slt5lqvwu-i0BCX6_UWF4o7uy4kVw7c29rdPsiLIkwM-26w',
  savedReviews:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuC2p8JrUt1fnHozXgiGD2jSABn47HP_rXcJzSlyejxk8lxJmTiDqDUPA6cPOk7M8-24kuO9UUg0Ljjpbv8bZlwvJyZnWVH72KRMhvFOL57hh8lHWwHmrTjYvYpHgyB3Z7lxOBWDYCsSQGFaTU1KHPyCAPmeyS5HSc9masa70Kx4GMYgqG1BJ9s5hND_Jdd9j06Odhdlc9c-pGHznZ5FwvLIn34y9Hi5n92N6zJOMQBMuZAhJQdRvkquOg',
  merchantCafe:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuAm63ZEemWbUrB_5h9Ij-SEaSZvBccybkbb55Wx2t5-hJww4m8tWKchYAGt9Z1z6iINEe11DhAqHnh3vHfDW2ubJRcMtJHlsnIQhefRVUKdV3mJz9xXR3U0HD7Z1sM-BwwjBmSCiiUphexp5WZZPOhWmr0Pfm-xl7cSgMcEYbvNIL8IjTd_GKHFBolNhZovmUcDuh5-H_OJSgqp8MZnI0ixE39WZcRBOVGTRqoEF_St8UPr7gWzI7LX1A',
  merchantRetail:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuBz0_tK5vpPRI9uX6MPXOOI1t7EbV0dHh2VzsuxWkbi4KUox-rjZG3FDOE-du4TVdeDTveiPmxKC9kG0M4Lk9onafyLqjhnyYECvdObxee3ie7ogY7iXKOnPS4Z_l3nSjgmwpYaKtUb-qL6SqfNXEZU63EJ_pNJ_MHzNuZQbN00EK31nE0cdfCRWXX-TKFsFnMNh2Kak8Q74wFu-C0Cisj_4LvzyJgb1X9bMNL1LPBU8jawuYFFFxNKCA',
  merchantOwner:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuAIBMNslXwC_lzD-mEs8J_Y2EBjgCR10rgvgK412xQyz6e1FjbSHVvz9MvfUDmlHky92VKTbZO88_vDAjjBRXMeq0J2Kwo5mxSLE7JvonE5bIPibLLoVq4mNAOPgNywJIqOFPlBp0bDhLnlQJ842No6L0jovywxv2jT7LLXzrj3wJeB03da5PocWwz5UEWPpb7sRYoDDOeo-yF99cmG5U9xgB03O1sTmRfUjqU1aNKVkwtl4dS-1wNV-w',
  successStorefront:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuBBS6f2StSn5jzvi7cW3Zwy6DxTkVU0VLWtEPEVLiBG8HnHEzNeN60vmytS1VD4pxHvNCrBXaztDntxLRpZsNGWmmV3aJMvDc64k2CRbcWH-fNRKZnC3T2yjxa640OuMxxpzOcI0nio10-A1grk9jj-C24CzgiGEk4836K1rSy3JpAymebH-FYW9z_X6ohGAyTGwGwVppNAiYGaSCHn4wRKAjc9g8jgpI1mnj7gUXranQWd-6PngMaDbQ',
} as const;

export const verifyBusinessCopy = {
  header: 'Verify Your Business',
  stageSetup: 'Setup',
  stageVerification: 'Verification',
  stageActivation: 'Activation',
  title: 'Verify your business',
  subtitle: 'Help us keep VEMTAP safe for customers and genuine businesses.',
  context:
    "You'll verify your identity and provide your business registration information where applicable.",
  whyTitle: 'Why Verification Matters',
  valueProtectTitle: 'Protect customers',
  valueProtectBody:
    'Helps prevent fake businesses and fraudulent deals across your local community.',
  valueTrustTitle: 'Build trust',
  valueTrustBody:
    'Verified businesses earn the verified badge and greater shopper confidence.',
  valueUnlockTitle: 'Unlock business features',
  valueUnlockBody:
    'Verification is required before participating in VEMTAP discovery and instant deals.',
  reassurance:
    'Verification builds safety for both you and your buyers. We keep your credentials strictly confidential and encrypted.',
  start: 'Start Verification',
  later: "I'll do this later",
  footnote:
    'You can continue setting up your business, but some features may remain unavailable until verification is completed.',
} as const;

export const verifyIdentityCopy = {
  header: 'Verify Your Identity',
  stepLabel: 'Step 1 of 2',
  title: 'Who are you?',
  subtitle:
    'Select a government-issued ID to verify your identity. This verifies the person operating this business account.',
  registryTitle: 'Official Identity Registry',
  registryBody: 'Connected with accredited verification services',
  nin: 'NIN',
  ninBadge: 'Recommended • Instant',
  ninBody: 'Fast digital verification via official NIMC database',
  licence: "Driver's Licence",
  licenceBody: 'Federal Road Safety Corps (FRSC) issued licence',
  passport: 'International Passport',
  passportBody: 'Nigerian Immigration Service (NIS) passport',
  privacyLead: 'Your personal identity information is protected by ',
  privacyHighlight: '256-bit bank-grade encryption',
  privacyTail: ' and only used for account authentication and regulatory compliance.',
  continue: 'Continue',
  speedHint: 'Instant identity verification in 30 seconds',
} as const;

export const idVerificationCopy = {
  header: 'Id Verification',
  pill: 'NIN Verification',
  step: 'Step 2 of 3',
  title: 'Enter your NIN details',
  subtitle:
    'Your information is used only for identity verification and fraud prevention.',
  ninLabel: 'National Identification Number (NIN)',
  ninInfoLabel: 'NIN Info',
  ninCounter: '11 digits',
  ninPlaceholder: 'e.g. 5041 2938 104',
  ninValue: '5041 2938 104',
  ussdLead: 'Dial ',
  ussdCode: '*346#',
  ussdTail: ' on your registered SIM to retrieve your NIN.',
  nameLabel: 'Full Legal Name (as shown on ID)',
  nameValue: 'Zainab Ahmed',
  uploadTitle: 'Upload or Snap Slip / Card',
  uploadBadge: 'Optional',
  uploadBody: 'Make sure the document is clear, well-lit, and all 4 corners are visible.',
  uploadAction: 'Take Photo or Upload Slip',
  uploadFileName: 'nin_slip_scan.jpg',
  removeFileLabel: 'Remove uploaded NIN slip',
  security:
    'Your information is securely encrypted and verified directly with official databases. VEMTAP never shares your sensitive ID records.',
  submit: 'Verify Identity',
  submitHint: 'Instant verification usually takes under 15 seconds.',
  infoTitle: 'About NIN Verification',
  infoBody:
    'Your 11-digit NIN is issued by NIMC. We validate your name against government registries for compliance.',
  closeInfoLabel: 'Close NIN verification information',
} as const;

export const idVerificationNeedsReviewCopy = {
  header: 'Id Verification Needs Review',
  title: "We couldn't verify your identity",
  subtitle:
    'Please check your information and try again. Minor mismatches or blurry scans are easy to fix.',
  reasonsTitle: 'Common reasons this happens',
  reasons: [
    "Information doesn't match official records",
    'Document details or photo could not be read clearly',
    "Document was cropped or corners weren't visible",
    'Official verification network is temporarily slow or unavailable',
  ],
  reassurance:
    "Don't worry — this does not affect your account or ability to use VEMTAP.",
  tryAgain: 'Try Again',
  useAnotherId: 'Use Another ID (Passport or Licence)',
  manualReview: 'Request Manual Review',
  manualReviewHint: 'Our compliance team will review your document within 24 hours',
} as const;

export const idVerificationSuccessCopy = {
  header: 'Id Verification Success',
  title: 'Identity verified',
  subtitle:
    "Your identity has been successfully verified. You're ready to proceed with business details.",
  identityStatus: 'Identity Status',
  verifiedBadge: 'Verified',
  personLabel: 'Verified Person',
  personValue: 'Zainab Ahmed',
  documentLabel: 'Document Type',
  documentValue: 'National ID (NIN)',
  referenceLabel: 'Document Reference',
  referenceValue: '•••• 4821',
  verifiedOn: 'Verified on Oct 18, 2024 at 10:45 AM',
  nextStage: 'NEXT STAGE',
  nextStep: 'Step 2 of 3',
  nextTitle: 'Business Registration',
  nextBody:
    'Tell us if your store or business has an official CAC corporate registration number.',
  continue: 'Continue to Business Registration',
  footer: 'Encrypted & securely stored via NDPR compliance',
} as const;

export const businessRegistrationCopy = {
  header: 'Business Registration',
  step: 'Step 2 of 2',
  title: 'Is your business registered?',
  subtitle:
    'Select whether your business is officially registered with the Corporate Affairs Commission (CAC).',
  registeredBadge: 'CAC Registered',
  registeredTitle: 'Yes, my business is registered',
  registeredBody:
    'I have a Registered Business Name, Limited Liability (LLC/Ltd), or Incorporated Trustee CAC registration.',
  registeredFootnoteLead: 'Unlocks official ',
  registeredFootnoteHighlight: 'Verified Business',
  registeredFootnoteTail: ' badge & higher reach',
  unregisteredBadge: 'Sole Trader / Unregistered',
  unregisteredTitle: "No, my business isn't registered",
  unregisteredBody:
    'I operate as an individual, artisan, or informal brand. I want to launch quickly without documents for now.',
  unregisteredFootnote: 'You can still sell, post deals & use all core VEMTAP tools',
  noPressureLead: 'No pressure:',
  noPressureBody:
    'You can always upload and verify your CAC registration certificate later under ',
  noPressureHighlight: 'Business Profile Settings',
  noPressureTail: '.',
  continue: 'Continue',
  footnote: 'Official CAC lookup integration is secure and encrypted',
} as const;

export const cacVerificationCopy = {
  header: 'Cac Verification',
  pill: 'CAC Verification',
  title: 'Enter your CAC registration details',
  subtitle:
    "We'll verify your business details directly against official Corporate Affairs Commission records.",
  registryTitle: 'Live Automated Registry',
  registryBody: 'Direct API lookup to Nigerian CAC registrar',
  registryBadge: 'Online',
  entityLabel: 'Business Entity Type',
  entities: [
    { id: 'BN', title: 'Business Name', caption: '(BN)' },
    { id: 'RC', title: 'Limited Co.', caption: '(RC)' },
    { id: 'IT', title: 'Incorp. Trustee', caption: '(IT)' },
  ],
  numberLabel: 'CAC Registration Number (RC / BN Number)',
  numberValid: 'Format valid',
  numberPlaceholder: 'e.g. BN-3491820',
  numberValue: 'BN-3491820',
  numberHint: 'Enter your RC, BN, or IT number as printed on your certificate.',
  nameLabel: 'Registered Business Name',
  namePlaceholder: 'Legal entity name',
  nameValue: 'Urban Grill & Bistro Ltd',
  nameHint: 'Must exactly match official Corporate Affairs Commission documentation.',
  uploadTitle: 'Upload CAC Certificate',
  uploadBadge: 'Optional',
  uploadBody:
    'Only required if automated registry lookup cannot retrieve your certificate.',
  uploadAction: 'Attach PDF or Photo',
  uploadActionHint: 'PDF, JPG, or PNG up to 10MB',
  uploadFileName: 'cac_certificate_doc.pdf',
  removeFileLabel: 'Remove uploaded CAC certificate',
  privacy:
    'Your registration number is verified with accredited corporate registries under NDPR privacy standards.',
  submit: 'Verify Business',
  notIncorporatedLead: 'Not incorporated yet?',
  notIncorporatedAction: 'Register your business first →',
} as const;

export const cacVerificationSuccessCopy = {
  header: 'Cac Verification Success',
  title: 'Business verified',
  subtitle:
    'Your business registration has been successfully verified against CAC registry records.',
  businessName: 'Urban Grill & Bistro',
  businessMeta: 'Victoria Island, Lagos • Restaurant & Bar',
  recordLabel: 'Official Record',
  recordLive: 'Live in Registry',
  nameLabel: 'Business Name',
  nameValue: 'Urban Grill & Bistro Ltd',
  cacLabel: 'CAC Registration',
  cacValue: 'CAC Verified (BN-3491820)',
  operatorLabel: 'Account Operator',
  operatorValue: 'Identity Verified (Zainab Ahmed)',
  badgeLabel: 'Storefront Trust Badge',
  badgeValue: 'Verified Business ✓',
  trustLead: 'Your business will now display the official ',
  trustHighlight: 'VEMTAP Verified',
  trustTail: ' badge on all storefront listings, deals, and customer search results.',
  continue: 'Continue to Final Review',
  footnote: 'Step 3 of 4 • Final setup takes less than 1 minute',
} as const;

export const youReVerifiedCopy = {
  header: 'Verification Complete',
  helpLabel: 'Help & Support',
  validatedBadge: 'Account 100% Validated',
  title: "You're verified",
  subtitleLead:
    'All required trust and compliance checks have been successfully completed for ',
  subtitleTail: '.',
  businessName: 'Urban Grill & Bistro',
  breakdownLabel: 'Verification Breakdown',
  confirmed: '4 / 4 Confirmed',
  pillars: [
    {
      icon: 'badge',
      title: 'Identity',
      tag: 'Verified',
      body: 'Operator: Zainab Ahmed',
    },
    {
      icon: 'domain',
      title: 'Business',
      tag: 'CAC verified',
      body: 'Registry: BN-3491820',
    },
    {
      icon: 'storefront',
      title: 'Business Location',
      tag: 'Added',
      body: 'Apo District, Abuja • 2 Branches Active',
    },
    {
      icon: 'palette',
      title: 'Business Profile',
      tag: 'Ready',
      body: 'Logo, Cover, Catalog & Deal Configured',
    },
  ],
  previewName: 'Urban Grill & Bistro',
  previewMeta: 'Live Catalog • 1 Active Welcome Voucher',
  previewStatus: 'Ready for consumer discovery',
  trustTitle: 'Official Trust Status',
  trustBody:
    'Your official VEMTAP Verified Business badge is now active. Your storefront will feature the verified trust checkmark across all customer discovery searches.',
  continue: 'Continue to Activation',
  previewAction: 'Preview Verified Storefront',
  readyNote: 'Your business is ready for the next step.',
  footer: 'Encrypted & securely stored via NDPR compliance standards.',
} as const;

export const verificationInProgressCopy = {
  header: 'Verification Review',
  helpLabel: 'Help & Support',
  statusPill: 'Application Under Review',
  title: 'Verification in progress',
  subtitle: "We're checking the information you provided. This may take a little while.",
  progressTitle: 'Review Progress',
  stepBadge: 'Step 3 of 4',
  steps: [
    {
      title: 'Identity submitted',
      body: 'Zainab Ahmed • NIN verified',
      state: 'done',
      trailingIcon: 'verified',
    },
    {
      title: 'Business information submitted',
      body: 'Urban Grill & Bistro • CAC documents received',
      state: 'done',
      trailingIcon: 'folderStar',
    },
    {
      title: 'Verification in progress',
      body: 'Registry cross-reference under review by compliance team',
      state: 'active',
      trailingIcon: null,
    },
    {
      title: 'VEMTAP verification complete',
      body: 'Official Verified badge activation',
      state: 'pending',
      trailingIcon: 'crown',
    },
  ],
  turnaroundTitle: 'Estimated Turnaround',
  turnaroundBody:
    "Most verifications are reviewed within 2 to 24 hours. We'll send a push notification and email once your review is completed.",
  keepGoingTitle: "You don't have to wait here!",
  keepGoingBadge: 'Ready',
  keepGoingBody:
    'You can continue configuring your storefront, adding products, and customizing your deals in the meantime.',
  continueSetup: 'Continue Setup',
  checkLater: 'Check Status Later',
  questions: 'Questions?',
  support: 'Contact Merchant Support',
} as const;

export const verificationStatusCenterCopy = {
  header: 'Business Verification Status Center',
  helpLabel: 'Help & Support',
  businessName: 'Urban Grill & Bistro',
  lastVerifiedLead: 'Last verified on Oct 18, 2024',
  trustTitle: 'Verified Business',
  trustTier: 'Tier 3 Merchant Tier',
  trustScore: '100% Compliant',
  pillars: [
    { icon: 'verified', title: 'Legal Entity', meta: 'Validated' },
    { icon: 'storefront', title: '2 Hubs', meta: 'Inspected' },
    { icon: 'shieldLock', title: 'Protection', meta: 'NDPR Active' },
  ],
  listTitle: 'Credentials & Standing',
  listCount: '4 of 4 active',
  credentials: [
    {
      icon: 'badge',
      title: 'Identity Verification',
      body: 'Zainab Ahmed • NIN (Ending in •••• 4821)',
      meta: 'Gov-issued ID • Biometric check passed',
      action: 'View Details',
      actionIcon: 'forward',
      status: 'Verified',
      statusIcon: 'check',
    },
    {
      icon: 'accountBalance',
      title: 'Business Registration (CAC)',
      body: 'Corporate Affairs Commission • BN-3491820',
      meta: 'Registration Date: 14 May 2021',
      action: 'View Certificate',
      actionIcon: 'forward',
      status: 'Verified',
      statusIcon: 'check',
    },
    {
      icon: 'pinDrop',
      title: 'Physical Business Locations',
      body: '2 Active Branches (Apo & Wuse II)',
      meta: 'Geofenced GPS beacon live',
      action: 'Manage Locations',
      actionIcon: 'forward',
      status: 'Verified',
      statusIcon: 'check',
    },
    {
      icon: 'bolt',
      title: 'Storefront Standing',
      body: 'Full access to hyper-local discovery, instant deals, and customer passes',
      meta: null,
      action: null,
      actionIcon: null,
      status: 'In Good Standing',
      statusIcon: 'dot',
    },
  ],
  boostTitle: 'Instant Consumer Trust Boost',
  boostBody:
    'Verified merchants receive 3.4x more foot traffic from local search suggestions.',
  updateTitle: 'Need to update something?',
  updateBody:
    'Changes to your business name, legal structure, or operating address may require verifying your credentials again to maintain the ',
  updateHighlight: 'Verified Business',
  updateTail: ' badge.',
  updateAction: 'Update Verification Information',
  dashboardAction: 'Continue to Business Dashboard',
  dashboardHint: 'Skip for now and start managing your business',
  auditLetterAction: 'Request Official Verification Letter / Audit Proof',
  auditLetterDisabledLabel:
    'Request Official Verification Letter / Audit Proof — not available yet',
  footer: 'Regulated under Nigerian Data Protection Regulation (NDPR).',
  sheetTitle: 'Verification Certificate',
  sheetSubtitle: 'Validated on Federal Database',
  sheetRegistrationLabel: 'Registration Number',
  sheetRegistrationValue: 'BN-3491820',
  sheetEntityLabel: 'Registered Entity',
  sheetEntityValue: 'Urban Grill & Bistro Ltd',
  sheetStatusLabel: 'Status',
  sheetStatusValue: 'Active & Verified',
  sheetHashLabel: 'Digital Hash',
  sheetHashValue: '#vm-8492048-ng',
  sheetDone: 'Done',
  certificateDetailsLabel: 'View details for',
} as const;

export const unregisteredBusinessCopy = {
  header: 'Unregistered Business',
  helpLabel: 'Help & Support',
  moodBadge: 'No worries at all',
  title: "That's okay",
  subtitle: 'You can still use VEMTAP if your business is not currently CAC registered.',
  identityLabel: 'Operator Identity',
  identityValue: 'Zainab Ahmed',
  identityStatus: 'Verified',
  cacLabel: 'CAC Registration',
  cacValue: 'Informal / Sole Trader',
  cacStatus: 'Not registered',
  scopeBody:
    "Your business may have access to some VEMTAP features, but it won't receive the Verified Business badge until the required business verification is completed.",
  canDoTitle: 'What you can do right now',
  canDo: [
    'Post deals and create daily flash offers',
    'Set up your storefront & share instant QR code',
    'Receive customer chat messages & bookings directly',
  ],
  reservedTitle: 'Reserved for CAC Verified',
  reserved: [
    'Official blue Verified Business checkmark on storefront',
    'Pinned placement in curated top neighborhood feeds',
  ],
  continue: 'Continue',
  learnMore: 'Learn about business verification',
  footnoteLead:
    'You can register your business with CAC and upgrade your status anytime under ',
  footnoteHighlight: 'Business Profile',
  footnoteTail: '.',
} as const;

export const planTrialOverviewCopy = {
  header: 'Subscription Plans',
  helpLabel: 'Help & Information',
  badge: 'Simple, transparent pricing',
  title: 'Choose how you want to grow with VEMTAP',
  subtitle: "Start free, experience VEMTAP, and continue when you're ready.",
  planLabel: 'Official Plan',
  planBadge: 'SME Preferred',
  planName: 'VEMTAP Growth',
  planPrice: '₦5,000',
  planCycle: '/ month',
  planBody: 'Everything you need to manage and grow your business on VEMTAP.',
  trialTitle: 'Includes 30-Day Free Trial',
  trialBody: 'No credit card or commitment required',
  features: [
    { label: 'Business profile & storefront presence', featured: false },
    { label: 'Products & services digital catalog', featured: false },
    { label: 'Deals, discounts & flash offers', featured: false },
    {
      label: 'Multiple business locations',
      featured: true,
      badge: 'Included',
    },
    { label: 'Business QR & Table NFC physical codes', featured: false },
    { label: 'Customer messaging & direct chat', featured: false },
    { label: 'Hyper-local customer discovery feed', featured: false },
    { label: 'Customer engagement & repeat visits', featured: false },
    { label: 'Loyalty & Tap rewards tools', featured: false },
    { label: 'Real-time revenue & visit analytics', featured: false },
    { label: 'Complete storefront & staff management', featured: false },
  ],
  breakdownToggle: 'View everything included (Full Breakdown)',
  breakdown: [
    {
      title: 'Storefront & Discovery',
      body: 'Custom domain routing, real-time hours, instant verified badge, and priority geo-listing across 5km radius.',
    },
    {
      title: 'Contactless Hardware Integration',
      body: 'Downloadable printable vector QR kits & sync-ready support for smart NFC tap plates.',
    },
    {
      title: 'Payments & Direct Settlements',
      body: 'Zero platform commission on cash settlements and support for direct Nigerian bank transfers.',
    },
    {
      title: 'Support & Business Concierge',
      body: 'WhatsApp dedicated merchant account manager & onboarding specialist assistance.',
    },
  ],
  startTrial: 'Start 30-Day Free Trial',
  subscribeNow: 'Subscribe Now (₦5,000/mo)',
  footnote: 'No credit card required to start your free trial. Cancel anytime.',
  addOns: 'Looking for Boosts or SMS? View paid add-ons',
  audience: 'Built for Nigerian retailers, restaurants, lounges, and service providers.',
} as const;

export const freeTrialConfirmationCopy = {
  header: 'Subscription Plans',
  helpLabel: 'Help & Information',
  title: 'Your 30-day trial starts now',
  subtitle:
    'Explore VEMTAP, add your products and services, create deals, manage your locations and see how customers interact with your business.',
  timelineTitle: 'Trial Timeline',
  timelineBadge: 'Risk Free',
  timeline: [
    {
      label: 'Today',
      meta: 'Trial Starts',
      body: 'Instant access to all features unlocked across your account.',
    },
    {
      label: 'Next 30 Days',
      meta: '100% Free',
      body: 'Full access, zero commitment, and cancel or pause anytime.',
    },
    {
      label: 'Day 30',
      meta: '₦5,000 / month',
      body: 'Continue with Growth. Only billed if you deliberately choose to upgrade.',
    },
  ],
  includedTitle: "What's included in your trial",
  includedBadge: 'All-inclusive',
  included: [
    { icon: 'storefront', label: 'Business profile', meta: null, wide: false },
    { icon: 'inventory', label: 'Products & services', meta: null, wide: false },
    { icon: 'localOffer', label: 'Deals & offers', meta: null, wide: false },
    { icon: 'hub', label: 'Multiple locations', meta: null, wide: false },
    { icon: 'qrCodeScanner', label: 'QR & smart tags', meta: null, wide: false },
    { icon: 'message', label: 'Customer messaging', meta: null, wide: false },
    { icon: 'nearMe', label: 'Hyper-local discovery', meta: null, wide: false },
    { icon: 'insights', label: 'Business analytics', meta: null, wide: false },
    {
      icon: 'loyalty',
      label: 'Customer loyalty & rewards',
      meta: 'Keep shoppers coming back',
      wide: true,
    },
  ],
  noCardTitle: 'No Card Required',
  noCardBody:
    'No payment card is required to start your trial. You will not be automatically charged.',
  categoriesLabel: 'Supported Merchant Categories',
  categoriesCount: 'Over 4,200 local spots',
  categoryCards: [
    { title: 'Cafes & Dining', meta: 'Smart orders active' },
    { title: 'Retail & Fashion', meta: 'Live discovery deals' },
  ],
  startTrial: 'Start My Free Trial',
  subscribeInstead: 'Subscribe Now Instead',
  subscribeInsteadPrice: '(₦5,000/mo)',
  footnote: 'Tap to proceed. Instant activation in 3 seconds.',
} as const;

export const trialActiveStatusCopy = {
  header: 'Subscription Plans',
  helpLabel: 'Help & Information',
  liveBadge: 'Live Subscription',
  subscriptionId: 'ID: #VEM-88204',
  title: 'VEMTAP Growth Trial Active',
  subtitle: "You're currently exploring VEMTAP Growth for free.",
  timelineLabel: 'Plan Timeline',
  daysRemaining: 'days remaining',
  usedLabel: 'Day 7 of 30 used',
  elapsedLabel: '23% elapsed',
  startedLabel: 'Oct 18, 2024',
  endsLabel: 'Nov 17, 2024',
  exploreDashboard: 'Explore My Business Dashboard',
  subscribeNow: 'Subscribe Now & Lock In Growth (₦5,000/mo)',
  includesTitle: 'Your active trial includes',
  includesBadge: 'All-Inclusive',
  includes: [
    {
      label: 'Multiple business locations active',
      meta: 'Apo, Wuse II branches live and verifiable',
    },
    { label: 'Products & services catalog', meta: null },
    { label: 'Live deals & customer vouchers', meta: null },
    { label: 'Hyper-local customer discovery', meta: null },
    { label: 'In-app direct messaging', meta: null },
    { label: 'Performance analytics & scan counts', meta: null },
    { label: 'Customer loyalty & Tap rewards', meta: null },
    { label: 'Official Business QR code', meta: null },
  ],
  guaranteeTitle: 'Gentle Guarantee',
  guaranteeBody:
    "We'll send you an in-app and email reminder 3 days before your trial ends. No unexpected surprises or charges.",
} as const;

export const trialEndingCopy = {
  header: 'Subscription Plans',
  helpLabel: 'Help & Information',
  title: 'Your VEMTAP trial is ending',
  bodyLead: 'Your free trial ends in ',
  bodyHighlight: '3 days',
  bodyTail: ' (Oct 21, 2024). Keep your momentum going without losing store visibility.',
  dayLabel: 'Day 27 of 30 completed',
  daysLeftBadge: '3 Days Left',
  storefrontLabel: 'Live Storefronts',
  storefrontCount: '2 active branches',
  storefrontName: 'Koffee & Co. Roasters',
  storefrontMeta: 'Apo Resettlement • Wuse II Branch',
  planBadge: 'Recommended Plan',
  planPrice: '₦5,000',
  planCycle: '/month',
  planTitle: 'Continue with VEMTAP Growth',
  planBody:
    'Continue using VEMTAP Growth to keep your business active on the VEMTAP network without interruption.',
  benefitsTitle: 'Key benefits to keep active:',
  benefits: [
    'Keep your business profile & storefront active',
    'Keep your deals visible to local shoppers',
    'Keep managing your branch locations (Apo & Wuse II)',
    'Continue engaging customers via direct in-app chat',
    'Continue using analytics, QR tap codes & loyalty tools',
  ],
  pricingNote:
    'Simple pricing: One plan covering all your storefronts. No hidden setup fees.',
  continue: 'Continue with Growth — ₦5,000/month',
  review: 'Review My Business',
  guarantee: 'Your account data and listings are never automatically deleted.',
} as const;

export const trialExpiredCopy = {
  header: 'Subscription Plans',
  helpLabel: 'Help & Information',
  title: 'Your VEMTAP trial has ended',
  subtitle:
    'Your business information is completely safe. Subscribe to VEMTAP Growth to continue using the full business experience.',
  dataTitle: 'Your Store Data is Secure',
  dataBody:
    'Your products, menu items, branch locations, and customer reviews are saved and ready to reactivate immediately.',
  assets: [
    { icon: 'inventory', label: '14 Items' },
    { icon: 'storefront', label: '2 Outlets' },
    { icon: 'starFilled', label: '4.9 (128)' },
  ],
  planBadge: 'Recommended Plan',
  planName: 'VEMTAP Growth',
  planPrice: '₦5,000',
  planCycle: '/ month',
  planTagline: 'Instant reactivation • No setup fee',
  planFeatures: [
    'Re-enable customer deal claims & discovery',
    'Re-activate QR code table passes',
    'Full multi-location access & staff permissions',
  ],
  activate: 'Activate Growth — ₦5,000/mo',
  viewBusiness: 'View My Business (Read-Only)',
  supportQuestion: 'Questions about your plan?',
  supportAction: 'Contact Merchant Support anytime',
} as const;

export const subscribeNowCopy = {
  header: 'Payment Method',
  helpLabel: 'Help & Information',
  tierBadge: 'Merchant Tier',
  zeroFeeBadge: 'Zero Setup Fee',
  title: 'Continue with VEMTAP Growth',
  subtitle: 'Activate your monthly subscription to keep your business running smoothly.',
  planBadge: 'POPULAR FOR RETAIL',
  planName: 'VEMTAP Growth',
  planPrice: '₦5,000',
  planCycle: '/ month',
  planCycleNote: 'Monthly subscription • Cancel anytime',
  perks: [
    'Multiple business locations included',
    'Unlimited products & services catalog',
    'Hyperlocal deal publishing & broadcast',
    'Customer direct messaging & fast orders',
    'Business analytics & loyalty rewards suite',
  ],
  storeReadyLabel: 'STORE READY',
  storeReadyTitle: 'Your storefront goes live',
  storeReadyBody: 'Direct customer discovery starts instantly upon activation.',
  methodTitle: 'Payment Method',
  methodBadge: 'Secured by 256-bit SSL',
  methods: [
    {
      id: 'paystack',
      title: 'Paystack / Flutterwave',
      badge: 'Fast',
      body: 'Debit Cards, Bank Transfer, USSD',
    },
    {
      id: 'virtual_account',
      title: 'Direct Bank Transfer',
      body: 'Instant virtual account generated in checkout',
    },
    {
      id: 'digital_wallet',
      title: 'Apple Pay / Google Pay',
      body: 'One-touch biometric payment authorization',
    },
  ],
  securityTitle: 'Bank-grade Security',
  securityBody:
    'Payments are securely processed through regulated PCI-DSS compliant gateways. VEMTAP never stores your card number.',
  billingTitle: 'Billing Summary',
  billingLine: 'Growth Subscription (1 mo)',
  billingLineValue: '₦5,000',
  vatLabel: 'VAT (7.5%)',
  vatBadge: 'Waived',
  vatValue: '₦0',
  totalLabel: 'Total Due Today',
  totalNote: 'Instant activation',
  totalValue: '₦5,000',
  pay: 'Pay ₦5,000 & Activate Growth',
  renewNote: 'Your subscription renews monthly at ₦5,000 until cancelled in settings.',
  termsAction: 'Terms & Subscription Policy',
  processingTitle: 'Connecting to Secure Gateway...',
  processingBody: 'Routing to checkout channel.',
} as const;

export const paymentSuccessCopy = {
  statusBadge: 'Payment Successful',
  title: "You're now on VEMTAP Growth",
  subtitle: 'Your business is active and ready to grow with VEMTAP.',
  storeName: 'Apo & Wuse II Hubs',
  storeStatus: 'Storefront live on discovery radars',
  locationsLabel: 'Locations',
  locationsValue: '2 Active',
  planName: 'VEMTAP Growth',
  planKind: 'Subscription Plan',
  planPrice: '₦5,000',
  planCycle: '/ month',
  ribbon: 'Active • Auto-renewing',
  ribbonBadge: 'Billed Monthly',
  transactionIdLabel: 'Transaction ID',
  transactionId: 'VT-SUB-982410',
  locationsRowLabel: 'Business Locations',
  locationsRowValue: 'Apo & Wuse II',
  paidOnLabel: 'Payment Date',
  paidOn: 'Today, Oct 18, 2024',
  nextBillingLabel: 'Next Billing Date',
  nextBilling: 'Nov 18, 2024',
  methodLabel: 'Payment Method',
  methodBrand: 'MC',
  methodValue: '•••• 4128',
  invoiceAction: 'Download Tax Invoice • PDF',
  benefitsTitle: 'Growth Benefits Unlocked',
  benefitsBadge: 'All 3 Ready',
  benefits: [
    {
      label: 'Verified storefront active on nearby feeds',
      meta: 'Visible to shoppers within 5km of Apo & Wuse II.',
    },
    {
      label: 'Unlimited deal creation & QR tap codes live',
      meta: 'One-tap redemption ready for counter checkout.',
    },
    {
      label: 'Customer direct messaging & orders unlocked',
      meta: 'Accept real-time inquiries and immediate orders.',
    },
  ],
  dashboard: 'Go to Business Dashboard',
  explore: 'Explore Growth Features',
  supportQuestion: 'Questions about billing?',
  supportAction: 'Contact Merchant Support',
} as const;

export const vemtapAddOnsCopy = {
  header: 'Paid Add Ons',
  helpLabel: 'Help & Information',
  eyebrowIcon: 'bolt',
  eyebrow: 'Flexible Power-Ups',
  subtitle:
    'Optional paid services when your business needs extra reach or specialized tools.',
  addOns: [
    {
      icon: 'rocket',
      badge: 'Hyperlocal Reach',
      badgeTone: 'success',
      title: 'Boost a Deal',
      body: 'Get more visibility for a specific deal in customer feeds and search results.',
      image: 'boostDeal',
      imageAlt:
        'Modern coffee shop display showing high customer engagement metrics and an elevated ranking badge.',
      stat: 'Up to 3.4x neighborhood impressions',
      statIcon: null,
      priceCaption: 'Starting from',
      price: '₦2,000',
      priceSuffix: null,
      action: 'Boost Deal',
      actionIcon: 'arrowForward',
      comingSoon: null,
      actionVariant: 'primary',
    },
    {
      icon: 'storefront',
      badge: 'Storefront Spotlight',
      badgeTone: 'brand',
      title: 'Promote My Business',
      body: 'Increase visibility for your business profile across the neighborhood discovery map.',
      image: 'promoteBusiness',
      imageAlt:
        'Map illustration with glowing location pins across a clean street layout showing local retail highlights.',
      stat: 'Top pin placement across 5km radius',
      statIcon: 'pinDrop',
      priceCaption: 'Starting from',
      price: '₦3,500',
      priceSuffix: null,
      action: 'Promote Business',
      actionIcon: 'arrowForward',
      comingSoon: null,
      actionVariant: 'primary',
    },
    {
      icon: 'sms',
      badge: 'Direct Marketing',
      badgeTone: 'neutral',
      title: 'SMS Credits',
      body: 'Send SMS campaigns and customer announcements when you need them.',
      image: null,
      imageAlt: null,
      stat: 'Instant delivery to opt-in patrons',
      statIcon: 'markChatRead',
      statValue: '99.8% rate',
      priceCaption: 'Bundles from',
      price: '₦1,500',
      priceSuffix: '/ 250 SMS',
      action: 'Buy SMS Credits',
      actionIcon: 'arrowForward',
      comingSoon: null,
      actionVariant: 'primary',
    },
    {
      icon: 'autoAwesome',
      badge: 'Smart Automation',
      badgeTone: 'neutral',
      title: 'AI Credits',
      body: 'Use VEMTAP AI-powered menu copy, review responses, and deal generator tools.',
      image: null,
      imageAlt: null,
      stat: null,
      statIcon: null,
      statValue: null,
      features: [
        { icon: 'restaurant', label: 'Menu Copy' },
        { icon: 'rateReview', label: 'Reviews' },
        { icon: 'localOffer', label: 'Deals' },
      ],
      priceCaption: 'Bundles from',
      price: '₦1,000',
      priceSuffix: '/ 100 Credits',
      action: 'Buy AI Credits',
      actionIcon: 'arrowForward',
      comingSoon: null,
      actionVariant: 'primary',
    },
    {
      icon: 'pointOfSale',
      badge: 'In-Store Payments',
      badgeTone: 'neutral',
      badgeSecondary: 'Coming Soon',
      title: 'POS Terminal & Hardware',
      body: 'All-in-one smart terminal for contactless NFC card payments and instant QR redemptions.',
      image: 'posHardware',
      imageAlt:
        'Handheld point of sale card reader showing a contactless tap animation on a cafe counter.',
      stat: null,
      statIcon: null,
      statValue: null,
      statLeadingLabel: 'Hardware Pack',
      priceCaption: null,
      price: null,
      priceSuffix: null,
      action: 'Explore POS (Waitlist)',
      actionIcon: 'notifications',
      comingSoon: 'Coming Soon',
      actionVariant: 'secondary',
    },
  ] as const,
  note: 'Add-ons are one-time or pay-as-you-go. They never alter your base',
  noteEmphasis: '₦5,000/mo Growth subscription',
} as const;
