import React from 'react';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import type { StyleProp, ViewStyle } from 'react-native';

/**
 * Icon names used across the VEMTAP design system.
 * Maps semantic glyphs to MaterialCommunityIcons (bundled in Expo Go).
 */
export const iconNames = {
  back: 'chevron-left',
  backIos: 'arrow-left',
  forward: 'chevron-right',
  arrowForward: 'arrow-right',
  nearMe: 'near-me',
  myLocation: 'crosshairs-gps',
  locationOn: 'map-marker',
  bolt: 'lightning-bolt',
  storefront: 'storefront-outline',
  bag: 'shopping-outline',
  shoppingBag: 'shopping',
  localMall: 'shopping',
  fire: 'fire',
  trendingUp: 'trending-up',
  verified: 'check-decagram',
  verifiedUser: 'shield-check',
  mail: 'email-outline',
  mailRead: 'email-check',
  lock: 'lock-outline',
  visibility: 'eye-outline',
  visibilityOff: 'eye-off-outline',
  google: 'google',
  person: 'account',
  edit: 'pencil',
  editLocation: 'map-marker-radius',
  info: 'information',
  check: 'check',
  checkCircle: 'check-circle',
  close: 'close',
  search: 'magnify',
  explore: 'compass',
  radar: 'radar',
  sync: 'sync',
  history: 'history',
  star: 'star',
  cafeFilled: 'coffee',
  restaurant: 'silverware-fork-knife',
  loyalty: 'sale',
  badge: 'card-account-details',
  wallet: 'wallet',
  savings: 'piggy-bank-outline',
  lightbulb: 'lightbulb-on-outline',
  receipt: 'receipt-text-outline',
  expandMore: 'chevron-down',
  autoAwesome: 'star-four-points',
  food: 'food',
  grill: 'grill',
  category: 'shape-outline',
  drag: 'drag-horizontal-variant',
  image: 'image-outline',
  tagEdit: 'tag-edit-outline',
  barcode: 'barcode-scan',
  productionLimits: 'package-variant',
  mapPin: 'map-marker-outline',
  delivery: 'truck-delivery-outline',
  blocked: 'package-variant-closed',
  confirmation: 'ticket-confirmation-outline',
  timer: 'timer-sand',
  rules: 'format-list-checks',
  gifting: 'gift-open',
  campaign: 'bullhorn-outline',
  dining: 'silverware-fork-knife',
  courier: 'moped',
  reservation: 'calendar-clock',
  printer: 'printer-outline',
  nfc: 'nfc',
  fullscreen: 'fullscreen',
  download: 'download-outline',
  sensors: 'access-point',
  electricBolt: 'lightning-bolt',
  addPhoto: 'image-plus',
  wellnessCategory: 'human-male-board-poll',
  facialCategory: 'face-woman-shimmer',
  mobileService: 'taxi',
  deliveryOptions: 'map-marker-path',
  sanitizer: 'spray-bottle',
  locationSchedule: 'calendar-edit',
  policy: 'shield-check',
  priceCheck: 'cash-check',
  activeNotifications: 'bell-ring',
  photoLibrary: 'image-multiple',
  catalog: 'view-list',
  localOffer: 'tag',
  pin: 'map-marker',
  distance: 'map-marker-distance',
  offer: 'tag-outline',
  devices: 'devices',
  fashion: 'tshirt-crew',
  groceries: 'cart-outline',
  spa: 'spa',
  cafe: 'coffee',
  notifications: 'bell',
  tune: 'tune',
  schedule: 'clock-outline',
  favorite: 'heart-outline',
  favoriteFilled: 'heart',
  comment: 'message-outline',
  share: 'share-variant',
  link: 'link-variant',
  copy: 'content-copy',
  send: 'send',
  message: 'message-text',
  whatsapp: 'whatsapp',
  instagram: 'instagram',
  x: 'twitter',
  more: 'dots-horizontal',
  listView: 'format-list-bulleted',
  gridView: 'view-grid',
  dashboard: 'view-dashboard',
  dashboardCustomize: 'tune-variant',
  thumbUp: 'thumb-up-outline',
  home: 'home-outline',
  bookmark: 'bookmark-outline',
  accountCircle: 'account-circle-outline',
  fitness: 'weight-lifter',
  homeLiving: 'sofa',
  automotive: 'car-wrench',
  eventAvailable: 'calendar-check',
  hourglass: 'timer-sand',
  touchApp: 'cursor-default-click',
  qrCodeScanner: 'qrcode-scan',
  localActivity: 'ticket-confirmation',
  rule: 'format-list-checks',
  block: 'block-helper',
  doNotDisturb: 'bell-off-outline',
  inventory: 'package-variant-closed',
  roomService: 'room-service',
  qrScan: 'qrcode-scan',
  help: 'help-circle-outline',
  support: 'account-supervisor-outline',
  password: 'form-textbox-password',
  fingerprint: 'fingerprint',
  phoneDevice: 'cellphone',
  tablet: 'tablet',
  sms: 'message-text-outline',
  fileDocument: 'file-document-outline',
  locationPrecision: 'navigation-variant-outline',
  logout: 'logout',
  delete: 'delete-outline',
  gift: 'gift-outline',
  trophy: 'star-four-points-outline',
  announcement: 'bullhorn-outline',
  shield: 'shield-outline',
  phone: 'phone-outline',
  voucher: 'ticket-confirmation-outline',
  qrCode: 'qrcode',
  doneAll: 'check-all',
  plus: 'plus',
  remove: 'minus',
  emoji: 'emoticon-outline',
  signal: 'signal-cellular-outline',
  groupAdd: 'account-multiple-plus-outline',
  payments: 'cash-multiple',
  pointOfSale: 'point-of-sale',
  rateReview: 'message-star-outline',
  markChatRead: 'message-check-outline',
  officeBuilding: 'office-building',
  folderStar: 'folder-star-outline',
  insights: 'chart-areaspline',
  hub: 'hub',
  layers: 'layers-outline',
  aspectRatio: 'aspect-ratio',
  camera: 'camera-outline',
  imagePlus: 'image-plus',
  starFilled: 'star',
  editNote: 'note-edit-outline',
  addLocation: 'map-marker-plus-outline',
  rocket: 'rocket-launch-outline',
  addBusiness: 'store-plus-outline',
  calendar: 'calendar-month',
  wine: 'glass-wine',
  plusCircle: 'plus-circle',
  openInNew: 'open-in-new',
  save: 'content-save-outline',
  web: 'web',
  alternateEmail: 'at',
  personPin: 'map-marker-account',
  contactSupport: 'headset',
  handshake: 'handshake-outline',
  shieldPerson: 'shield-account',
  directionsCar: 'car',
  passport: 'passport-biometric',
  book: 'book-open-outline',
  accountBalance: 'bank-outline',
  domain: 'domain',
  palette: 'palette-outline',
  pinDrop: 'map-marker-radius-outline',
  crown: 'crown',
  checkBold: 'check-bold',
  folder: 'folder-outline',
  clockLock: 'lock-clock',
  cloudDone: 'cloud-check-outline',
  pushPin: 'pin-outline',
  forum: 'forum-outline',
  emoticonHappy: 'emoticon-happy-outline',
  domainOff: 'domain-off',
  shieldLock: 'shield-lock-outline',
  shieldStar: 'shield-star-outline',
  fileEdit: 'file-edit-outline',
  blur: 'blur',
  cropFree: 'crop-free',
  wifiAlert: 'wifi-alert',
  shieldKey: 'shield-key-outline',
  restore: 'restore',
  creditCard: 'credit-card-outline',
  contactless: 'contactless-payment-circle',
  autorenew: 'autorenew',
  flag: 'flag-outline',
  bellRing: 'bell-ring-outline',
  swapHoriz: 'swap-horizontal',
  northEast: 'arrow-top-right',
  store: 'store',
  deck: 'table-furniture',
  wifi: 'wifi',
  localParking: 'parking',
  storeMallDirectory: 'storefront',
  group: 'account-group',
  call: 'phone',
  checkIn: 'clipboard-check',
} as const;

export type IconName = keyof typeof iconNames;

export interface IconProps {
  name: IconName;
  size?: number;
  color?: string;
  style?: StyleProp<ViewStyle>;
}

export function Icon({ name, size = 20, color, style }: IconProps) {
  return (
    <MaterialCommunityIcons
      allowFontScaling={false}
      name={iconNames[name]}
      size={size}
      color={color}
      selectable={false}
      style={style}
    />
  );
}
